/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void)
{
	uint16_t sizeOfChar = sizeof(char);
	uint16_t sizeOfShort = sizeof(short);
	uint16_t sizeOfInt = sizeof(int);
	uint16_t sizeOfLong = sizeof(long);
	uint16_t sizeOfLongLong = sizeof(long long);
	uint16_t sizeOfDouble = sizeof(double);

	/* Debug Expression Table
	sizeOfChar	uint16_t	1
	sizeOfShort	uint16_t	2
	sizeOfInt	uint16_t	4
	sizeOfLong	uint16_t	4
	sizeOfLongLong	uint16_t	8
	sizeOfDouble	uint16_t	8
	*/

    /* Loop forever */
	for(;;);
}
